# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/realm/SwiftLint
    rev: 0.54.0
    hooks:
      - id: swiftlint
        args: ["--strict", "--config", ".swiftlint.yml"]

  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.53.2
    hooks:
      - id: swiftformat
        args: ["."]

  - repo: https://github.com/tricycle/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: "Package.resolved|.*.lock"
